<p><font size="6"><b>Scientific Python fundamentals</b></font></p>

> *Introduction to GIS scripting*  
> *May, 2017*

> *© 2017, Stijn Van Hoey (<mailto:stijnvanhoey@gmail.com>). Licensed under [CC BY 4.0 Creative Commons](http://creativecommons.org/licenses/by/4.0/)*


## Numpy

In [88]:
import numpy as np

### Creating numpy array

In [89]:
np.array([1, 1.5, 2, 2.5])  #np.array(anylist)

array([ 1. ,  1.5,  2. ,  2.5])

In [90]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [91]:
np.linspace(5, 9, 3)

array([ 5.,  7.,  9.])

In [92]:
np.zeros((5, 2)), np.ones(5)

(array([[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]), array([ 1.,  1.,  1.,  1.,  1.]))

In [93]:
np.zeros((5, 2)).shape, np.zeros((5, 2)).size

((5, 2), 10)

### Slicing

In [96]:
my_array = np.random.randint(2, 10, 10)
my_array

array([4, 6, 3, 9, 9, 7, 4, 4, 5, 3])

In [97]:
my_array[-2:]

array([5, 3])

Assign new values to items

In [98]:
my_array[0:7:2]

array([4, 3, 9, 4])

In [99]:
my_array[:2] = 10
my_array

array([10, 10,  3,  9,  9,  7,  4,  4,  5,  3])

In [100]:
my_array = my_array.reshape(5, 2)
my_array

array([[10, 10],
       [ 3,  9],
       [ 9,  7],
       [ 4,  4],
       [ 5,  3]])

In [101]:
my_array[0, :]

array([10, 10])

### Element-wise operations

In [102]:
my_array = np.random.randint(2, 10, 10)

In [103]:
my_array%3  # == 0

array([2, 0, 1, 2, 2, 2, 1, 0, 0, 0])

In [105]:
np.exp(my_array), np.sin(my_array)

(array([  148.4131591 ,   403.42879349,    54.59815003,  2980.95798704,
         2980.95798704,  2980.95798704,  1096.63315843,  8103.08392758,
           20.08553692,    20.08553692]),
 array([-0.95892427, -0.2794155 , -0.7568025 ,  0.98935825,  0.98935825,
         0.98935825,  0.6569866 ,  0.41211849,  0.14112001,  0.14112001]))

In [106]:
np.max(my_array)

9

In [107]:
np.cumsum(my_array) == my_array.cumsum()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [108]:
my_array.max(axis=0)

9

In [109]:
my_array * my_array  # element-wise

array([25, 36, 16, 64, 64, 64, 49, 81,  9,  9])

<div class="alert alert-info">
    <b>REMEMBER</b>: The operations do work on all elements of the array at the same time, you don't need a <strike>`for` loop<strike>
</div>

In [110]:
a_list = range(1000)
%timeit [i**2 for i in a_list]

1000 loops, best of 3: 397 µs per loop


In [111]:
an_array = np.arange(1000)
%timeit an_array**2

The slowest run took 35.73 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.48 µs per loop


### Boolean indexing and filtering (!)

In [112]:
row_array = np.random.randint(1, 20, 10)
row_array

array([16,  6, 17, 14, 10, 11,  2, 11, 13, 13])

Conditions can be checked (element-wise):

In [113]:
row_array > 5

array([ True,  True,  True,  True,  True,  True, False,  True,  True,  True], dtype=bool)

In [114]:
boolean_mask = row_array > 5

You can use this as a filter to select elements of an array:

In [115]:
row_array[boolean_mask]

array([16,  6, 17, 14, 10, 11, 11, 13, 13])

or, also to change the values in the array corresponding to these conditions:

In [116]:
row_array[boolean_mask] = 20
row_array

array([20, 20, 20, 20, 20, 20,  2, 20, 20, 20])

in short - making the values equal to 20 now -20:

In [117]:
row_array[row_array == 20] = -20
row_array

array([-20, -20, -20, -20, -20, -20,   2, -20, -20, -20])

This requires some practice...

In [118]:
AR = np.random.randint(0, 20, 15)
AR

array([ 3, 13,  4,  0, 11,  3,  0, 10, 13,  2, 16, 17, 13,  6, 11])

<div class="alert alert-success">
    <b>EXERCISE</b>: Count the number of values in AR that are larger than 10 (note: you can count with True = 1 and False = 0)
</div>

In [119]:
sum(AR > 10)

7

<div class="alert alert-success">
    <b>EXERCISE</b>: Change all even numbers of `AR` into zero-values.
</div>

In [120]:
AR[AR%2 == 0] = 0
AR

array([ 3, 13,  0,  0, 11,  3,  0,  0, 13,  0,  0, 17, 13,  0, 11])

<div class="alert alert-success">
    <b>EXERCISE</b>: Change all even positions of matrix AR into 30 values
</div>

In [121]:
AR[1::2] = 30
AR

array([ 3, 30,  0, 30, 11, 30,  0, 30, 13, 30,  0, 30, 13, 30, 11])

<div class="alert alert-success">
    <b>EXERCISE</b>: Select all values above the 75th percentile of the following array AR2 ad take the square root of these values
</div>

In [122]:
AR2 = np.random.random(10)
AR2

array([ 0.86082658,  0.42308315,  0.98334737,  0.36392312,  0.54205933,
        0.73762625,  0.72091781,  0.09150791,  0.09216173,  0.53210831])

In [123]:
np.sqrt(AR2[AR2 > np.percentile(AR2, 75)])

array([ 0.9278074 ,  0.99163873,  0.8588517 ])

<div class="alert alert-success">
    <b>EXERCISE</b>: Convert all values -99 of the array AR3 into Nan-values (Note that Nan values can be provided in float arrays as `np.nan`)
</div>

In [124]:
AR3 = np.array([-99., 2., 3., 6., 8, -99., 7., 5., 6., -99.])

In [125]:
AR3[AR3 == -99.] = np.nan
AR3

array([ nan,   2.,   3.,   6.,   8.,  nan,   7.,   5.,   6.,  nan])

Ready for some real **Pandas!**